import { MapContainer, CircleMarker, Polyline, TileLayer, useMap } from 'react-leaflet'
import { useEffect, useState } from 'react'
import { Pause, Play, RotateCcw, Truck } from 'lucide-react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { api, trackingStreamUrl, type TrackingPosition } from '@/lib/api'
import { toast } from 'sonner'

function Follow({ position }: { position: TrackingPosition }) { const map=useMap(); useEffect(()=>{map.fitBounds([[position.latitud,position.longitud],[position.destino_latitud,position.destino_longitud]],{padding:[30,30]})},[map,position]); return null }

export function TrackingPanel({ assignmentId, admin=false }: { assignmentId:number; admin?:boolean }) {
 const client=useQueryClient(); const [playing,setPlaying]=useState(false)
 const query=useQuery({queryKey:['tracking',assignmentId],queryFn:()=>api.tracking(assignmentId),retry:false,refetchInterval:playing?2500:false})
 const step=useMutation({mutationFn:(progress:number)=>api.demoTracking(assignmentId,progress),onSuccess:data=>client.setQueryData(['tracking',assignmentId],data),onError:()=>toast.error('No pudimos actualizar la simulación.')})
 useEffect(()=>{if(!admin||!playing)return;const timer=setInterval(()=>{const current=(client.getQueryData<TrackingPosition>(['tracking',assignmentId])?.progreso??0);if(current>=100){setPlaying(false);return}step.mutate(Math.min(100,current+10))},2500);return()=>clearInterval(timer)},[admin,playing,assignmentId,client])
 useEffect(()=>{let stopped=false;let controller:AbortController|undefined;async function connect(){controller=new AbortController();try{const token=localStorage.getItem('campo_token');const response=await fetch(trackingStreamUrl(assignmentId),{headers:token?{Authorization:`Bearer ${token}`}:{},signal:controller.signal});if(!response.ok||!response.body)throw new Error('stream');const reader=response.body.getReader();const decoder=new TextDecoder();let buffer='';while(!stopped){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});const events=buffer.split('\n\n');buffer=events.pop()??'';for(const event of events){const line=event.split('\n').find(item=>item.startsWith('data: '));if(line)client.setQueryData(['tracking',assignmentId],JSON.parse(line.slice(6)) as TrackingPosition)}}}catch{if(!stopped)setTimeout(connect,3000)}}void connect();return()=>{stopped=true;controller?.abort()}},[assignmentId,client])
 const reset=()=>step.mutate(0); const position=query.data
 if(!position&&admin)return <div className='rounded-2xl border bg-white p-5'><button onClick={()=>step.mutate(0)} className='flex h-11 items-center gap-2 rounded-xl bg-emerald-500 px-4 font-bold'><Play size={18}/>Preparar simulación</button></div>
 if(!position)return <div className='rounded-2xl bg-slate-100 p-8 text-center text-sm text-slate-500'>Ubicación no disponible.</div>
 return <div className='space-y-3'><div className='relative h-[390px] overflow-hidden rounded-2xl border bg-slate-100'><MapContainer center={[position.latitud,position.longitud]} zoom={12} className='h-full w-full'><TileLayer attribution='&copy; OpenStreetMap contributors' url='https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png'/><Follow position={position}/><Polyline positions={[[position.latitud+.08*(position.progreso/100),position.longitud-.08*(position.progreso/100)],[position.latitud,position.longitud],[position.destino_latitud,position.destino_longitud]]} pathOptions={{color:'#0891b2',dashArray:'7 8'}}/><CircleMarker center={[position.latitud,position.longitud]} radius={10} pathOptions={{fillColor:'#0f766e',fillOpacity:1,color:'#fff',weight:3}}/><CircleMarker center={[position.destino_latitud,position.destino_longitud]} radius={9} pathOptions={{fillColor:'#f59e0b',fillOpacity:1,color:'#fff',weight:3}}/></MapContainer><span className='absolute left-3 top-3 z-[500] rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900'>{position.fuente==='simulacion'?'SIMULACIÓN DEMO':'UBICACIÓN GPS'}</span></div><div className='rounded-xl border bg-white p-4'><div className='flex items-center justify-between text-sm'><span className='flex items-center gap-2 font-semibold'><Truck size={18}/>Vehículo en ruta</span><b>{position.progreso}%</b></div><div className='mt-3 h-2 overflow-hidden rounded-full bg-slate-100'><div className='h-full bg-emerald-500 transition-all' style={{width:`${position.progreso}%`}}/></div><p className='mt-2 text-xs text-slate-500'>Actualizado {new Date(position.fecha_hora).toLocaleTimeString('es-BO')}</p>{admin&&<div className='mt-4 flex gap-2'><button onClick={()=>setPlaying(v=>!v)} className='flex h-10 items-center gap-2 rounded-xl bg-slate-950 px-4 text-sm font-bold text-white'>{playing?<><Pause size={16}/>Pausar</>:<><Play size={16}/>{position.progreso?'Reanudar':'Iniciar'}</>}</button><button onClick={reset} className='flex h-10 items-center gap-2 rounded-xl border px-4 text-sm font-bold'><RotateCcw size={16}/>Reiniciar</button></div>}</div></div>
}
