import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { CalendarClock, CheckCircle, MapPin, MapPinCheck, Navigation, PackageCheck, Truck } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'
import { toast } from 'sonner'
import { useAuth } from '@/app/auth'
import { Card, ErrorState, Skeleton } from '@/components/ui'
import { api, errorMessage, type AsignacionEstado } from '@/lib/api'
import { TrackingPanel } from '@/components/TrackingPanel'

export function DriverPage({ view = 'home' }: { view?: 'home' | 'route' | 'history' | 'profile' }) {
  const { user } = useAuth(); const queryClient = useQueryClient()
  const watchId=useRef<number|null>(null); const [sharing,setSharing]=useState(false); const [lastGps,setLastGps]=useState<Date>()
  useEffect(()=>()=>{if(watchId.current!==null)navigator.geolocation.clearWatch(watchId.current)},[])
  const query = useQuery({ queryKey: ['driver-assignments'], queryFn: api.driverAssignments })
  const active = query.data?.find(item => !['entregada', 'cancelada'].includes(item.estado))
  const change = useMutation({ mutationFn: ({id,estado}:{id:number;estado:AsignacionEstado}) => api.driverStatus(id, estado), onSuccess: () => { toast.success('Estado actualizado'); void queryClient.invalidateQueries({queryKey:['driver-assignments']}) }, onError: e => toast.error(errorMessage(e)) })
  if (view === 'profile') return <section><h1 className='text-2xl font-bold'>Mi perfil</h1><Card className='mt-5 p-5'><p className='font-semibold'>{user?.nombre}</p><p className='text-sm text-slate-500'>{user?.email}</p><p className='mt-4 text-xs font-bold uppercase text-emerald-700'>Conductor</p></Card></section>
  if (query.isPending) return <Skeleton className='h-72 w-full'/>
  if (query.isError) return <ErrorState title='No pudimos cargar tus entregas' onRetry={() => void query.refetch()}/>
  if (view === 'history') { const history=query.data?.filter(x=>x.estado==='entregada')??[]; return <section><h1 className='text-2xl font-bold'>Historial</h1><div className='mt-5 space-y-3'>{history.map(x=><Card key={x.id_asignacion} className='p-4'><p className='font-bold'>{x.pedido.codigo}</p><p className='text-sm text-slate-500'>{x.pedido.ubicacion.ciudad} · Entregada</p></Card>)}{!history.length&&<Card className='p-8 text-center text-slate-500'>Aún no tienes entregas completadas.</Card>}</div></section> }
  if (!active) return <section><h1 className='text-2xl font-bold'>Buenos días, {user?.nombre?.split(' ')[0]}</h1><Card className='mt-6 p-10 text-center'><PackageCheck className='mx-auto text-emerald-600' size={34}/><p className='mt-4 font-semibold'>No tienes entregas asignadas en este momento.</p></Card></section>
  const startGps=()=>{if(!navigator.geolocation)return toast.error('Geolocalización no disponible.');watchId.current=navigator.geolocation.watchPosition(pos=>{api.publishPosition(active.id_asignacion,{latitud:pos.coords.latitude,longitud:pos.coords.longitude,precision_m:pos.coords.accuracy}).then(()=>{setSharing(true);setLastGps(new Date())}).catch(e=>toast.error(errorMessage(e)))},()=>toast.error('No pudimos acceder a tu ubicación.'),{enableHighAccuracy:true,maximumAge:5000})}
  const stopGps=()=>{if(watchId.current!==null)navigator.geolocation.clearWatch(watchId.current);watchId.current=null;setSharing(false)}
  if (view === 'route') return <section><h1 className='text-2xl font-bold'>Ruta de entrega</h1><p className='mt-1 text-sm text-slate-500'>{active.pedido.ubicacion.direccion}, {active.pedido.ubicacion.ciudad}</p><div className='mt-5'><TrackingPanel assignmentId={active.id_asignacion}/></div><div className='mt-4 rounded-xl border bg-white p-4'>{sharing?<><p className='text-sm font-bold text-emerald-700'>● Ubicación compartida</p><p className='mt-1 text-xs text-slate-500'>Última actualización {lastGps?.toLocaleTimeString('es-BO')}</p><button onClick={stopGps} className='mt-3 h-10 rounded-xl border px-4 text-sm font-bold'>Detener ubicación</button></>:<button onClick={startGps} className='flex h-11 items-center gap-2 rounded-xl bg-emerald-500 px-4 font-bold'><Navigation size={18}/>Compartir mi ubicación</button>}</div><p className='mt-3 rounded-xl bg-amber-50 p-3 text-sm text-amber-800'>La distancia y ETA aparecerán cuando exista una ruta calculada.</p></section>
  const action = active.estado === 'asignada' ? {label:'Aceptar entrega',estado:'aceptada' as AsignacionEstado,icon:CheckCircle} : active.estado === 'aceptada' ? {label:'Iniciar viaje',estado:'en_camino' as AsignacionEstado,icon:Navigation} : active.estado === 'en_camino' ? {label:'Llegué al destino',estado:'llegue' as AsignacionEstado,icon:MapPinCheck} : active.estado === 'llegue' ? {label:'Confirmar entrega',estado:'entregada' as AsignacionEstado,icon:PackageCheck} : null
  return <section><p className='text-sm font-semibold text-emerald-700'>JORNADA ACTIVA</p><h1 className='mt-1 text-2xl font-bold'>Buenos días, {user?.nombre?.split(' ')[0]}</h1><Card className='mt-6 overflow-hidden'><div className='bg-slate-950 p-5 text-white'><p className='text-xs font-bold uppercase tracking-wider text-emerald-400'>Entrega actual</p><div className='mt-2 flex items-center justify-between'><h2 className='text-xl font-bold'>{active.pedido.codigo}</h2><span className='rounded-full bg-white/10 px-3 py-1 text-xs'>{active.estado.replace('_',' ')}</span></div></div><div className='space-y-4 p-5'><p className='flex gap-3'><MapPin className='text-emerald-600'/><span><b>{active.pedido.ubicacion.ciudad}</b><br/><span className='text-sm text-slate-500'>{active.pedido.ubicacion.direccion}</span></span></p><p className='flex gap-3 text-sm'><Truck className='text-slate-400'/>{active.vehiculo.placa}</p><p className='flex gap-3 text-sm'><CalendarClock className='text-slate-400'/>{active.pedido.peso_kg} kg</p>{action&&<button disabled={change.isPending} onClick={()=>change.mutate({id:active.id_asignacion,estado:action.estado})} className='flex h-12 w-full items-center justify-center gap-2 rounded-xl bg-emerald-500 font-bold'><action.icon size={20}/>{action.label}</button>}</div></Card></section>
}
