import { zodResolver } from '@hookform/resolvers/zod'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { ColumnDef } from '@tanstack/react-table'
import { Edit3, Gauge, LoaderCircle, Plus, Search, Trash2, Truck } from 'lucide-react'
import { useMemo, useState } from 'react'
import { useForm } from 'react-hook-form'
import { toast } from 'sonner'
import { z } from 'zod'
import { Badge, Button, Card, ConfirmDialog, DataTable, EmptyState, ErrorState, Field, Input, LoadingTable, Modal, PageHeader, Pagination, Select } from '@/components/ui'
import { api, errorMessage, type Vehiculo } from '@/lib/api'

const schema = z.object({ placa: z.string().trim().min(1, 'La placa es obligatoria'), capacidad_kg: z.string().refine((value) => Number(value) > 0, 'La capacidad debe ser mayor a cero'), rendimiento_km_l: z.string().refine((value) => Number(value) > 0, 'El rendimiento debe ser mayor a cero'), disponible: z.boolean() })
type Values = z.infer<typeof schema>

function VehicleForm({ vehicle, close }: { vehicle?: Vehiculo; close: () => void }) {
  const client = useQueryClient()
  const { register, handleSubmit, formState: { errors } } = useForm<Values>({ resolver: zodResolver(schema), mode: 'onBlur', defaultValues: { placa: vehicle?.placa ?? '', capacidad_kg: vehicle?.capacidad_kg == null ? '' : String(vehicle.capacidad_kg), rendimiento_km_l: vehicle?.rendimiento_km_l == null ? '' : String(vehicle.rendimiento_km_l), disponible: vehicle?.disponible ?? true } })
  const save = useMutation({ mutationFn: (values: Values) => { const payload = { placa: values.placa.toUpperCase(), capacidad_kg: Number(values.capacidad_kg), rendimiento_km_l: Number(values.rendimiento_km_l), disponible: values.disponible }; return vehicle ? api.editarVehiculo(vehicle.id_vehiculo, payload) : api.crearVehiculo(payload) }, onSuccess: async () => { toast.success(vehicle ? 'Vehículo actualizado correctamente' : 'Vehículo registrado correctamente'); await Promise.all([client.invalidateQueries({ queryKey: ['vehiculos'] }), client.invalidateQueries({ queryKey: ['resumen'] })]); close() }, onError: (error) => toast.error(errorMessage(error)) })
  return <form onSubmit={handleSubmit((values) => save.mutate(values))} className='space-y-4' noValidate><Field label='Placa' error={errors.placa?.message} required><Input {...register('placa')} className='uppercase' placeholder='TJA-300' /></Field><div className='grid gap-4 sm:grid-cols-2'><Field label='Capacidad (kg)' error={errors.capacidad_kg?.message} required><Input {...register('capacidad_kg')} type='number' min='0.01' step='0.01' placeholder='500' /></Field><Field label='Rendimiento (km/L)' error={errors.rendimiento_km_l?.message} required><Input {...register('rendimiento_km_l')} type='number' min='0.01' step='0.01' placeholder='11' /></Field></div><label className='flex cursor-pointer items-center justify-between gap-4 rounded-xl border border-slate-200 p-4'><span><span className='block text-sm font-semibold text-slate-800'>Disponible</span><span className='mt-0.5 block text-xs text-slate-500'>Puede recibir nuevas asignaciones.</span></span><input {...register('disponible')} type='checkbox' className='h-5 w-5 rounded border-slate-300 accent-emerald-500' /></label><div className='flex justify-end gap-3 pt-2'><Button type='button' variant='secondary' onClick={close}>Cancelar</Button><Button type='submit' disabled={save.isPending}>{save.isPending && <LoaderCircle className='animate-spin' size={16} />}Guardar vehículo</Button></div></form>
}

export function VehiculosPage() {
  const client = useQueryClient(); const [page, setPage] = useState(1); const [search, setSearch] = useState(''); const [availability, setAvailability] = useState(''); const [editing, setEditing] = useState<Vehiculo | 'new' | null>(null); const [deleting, setDeleting] = useState<Vehiculo | null>(null)
  const query = useQuery({ queryKey: ['vehiculos', page, search, availability], queryFn: () => api.vehiculos({ page, page_size: 10, q: search, disponible: availability === '' ? undefined : availability === 'true', sort_by: 'placa', sort_order: 'asc' }) })
  const remove = useMutation({ mutationFn: (id: number) => api.eliminarVehiculo(id), onSuccess: async () => { toast.success('Vehículo eliminado correctamente'); setDeleting(null); await Promise.all([client.invalidateQueries({ queryKey: ['vehiculos'] }), client.invalidateQueries({ queryKey: ['resumen'] })]) }, onError: (error) => toast.error(errorMessage(error)) })
  const columns = useMemo<ColumnDef<Vehiculo, unknown>[]>(() => [
    { accessorKey: 'placa', header: 'Vehículo', cell: ({ row }) => <div className='flex items-center gap-3'><span className='grid h-9 w-9 place-items-center rounded-xl bg-cyan-50 text-cyan-700'><Truck size={17} /></span><span className='font-mono text-sm font-bold text-slate-900'>{row.original.placa}</span></div> },
    { accessorKey: 'capacidad_kg', header: 'Capacidad', cell: ({ row }) => <span>{Number(row.original.capacidad_kg).toLocaleString('es-BO')} kg</span> },
    { accessorKey: 'rendimiento_km_l', header: 'Rendimiento', cell: ({ row }) => <span className='inline-flex items-center gap-1.5'><Gauge size={15} />{Number(row.original.rendimiento_km_l).toLocaleString('es-BO')} km/L</span> },
    { accessorKey: 'disponible', header: 'Disponibilidad', cell: ({ row }) => <Badge value={row.original.disponible ? 'disponible' : 'no_disponible'} /> },
    { id: 'ubicacion', header: 'Ubicación', cell: () => <span className='text-xs text-slate-500'>Ubicación no disponible</span> },
    { id: 'actions', header: () => <span className='sr-only'>Acciones</span>, cell: ({ row }) => <div className='flex justify-end gap-1'><Button variant='ghost' size='icon' className='h-9 w-9' aria-label={`Editar ${row.original.placa}`} onClick={() => setEditing(row.original)}><Edit3 size={17} /></Button><Button variant='ghost' size='icon' className='h-9 w-9 text-rose-600 hover:bg-rose-50' aria-label={`Eliminar ${row.original.placa}`} onClick={() => setDeleting(row.original)}><Trash2 size={17} /></Button></div> },
  ], [])
  return <div className='space-y-6'><PageHeader eyebrow='Recursos operativos' title='Vehículos' description='Gestiona capacidad, rendimiento y disponibilidad de la flota.' action={<Button onClick={() => setEditing('new')}><Plus size={17} />Nuevo vehículo</Button>} /><Card><div className='flex flex-col gap-3 border-b border-slate-100 p-4 sm:flex-row'><label className='relative flex-1'><span className='sr-only'>Buscar vehículos</span><Search className='absolute left-3 top-3 text-slate-400' size={18} /><Input value={search} onChange={(event) => { setSearch(event.target.value); setPage(1) }} className='pl-10' placeholder='Buscar por placa…' /></label><Select aria-label='Filtrar disponibilidad' value={availability} onChange={(event) => { setAvailability(event.target.value); setPage(1) }} className='sm:w-52'><option value=''>Toda disponibilidad</option><option value='true'>Disponibles</option><option value='false'>No disponibles</option></Select></div>
      {query.isPending ? <LoadingTable label='Cargando vehículos' /> : query.isError ? <ErrorState title='No pudimos cargar los vehículos' message={errorMessage(query.error)} onRetry={() => void query.refetch()} /> : !query.data.items.length ? <EmptyState title={search || availability ? 'No encontramos vehículos' : 'Aún no hay vehículos'} description={search || availability ? 'Prueba cambiando los filtros de búsqueda.' : 'Agrega el primer vehículo para comenzar a planificar rutas.'} action={!search && !availability && <Button onClick={() => setEditing('new')}><Plus size={16} />Nuevo vehículo</Button>} /> : <><div className='hidden sm:block'><DataTable data={query.data.items} columns={columns} getRowLabel={(row) => `Vehículo ${row.placa ?? 'sin placa'}`} /></div><div className='divide-y divide-slate-100 sm:hidden'>{query.data.items.map((item) => <article key={item.id_vehiculo} className='p-4'><div className='flex items-start justify-between gap-3'><div><p className='font-mono font-bold text-slate-900'>{item.placa ?? 'Sin placa'}</p><p className='mt-1 text-xs text-slate-500'>{Number(item.capacidad_kg).toLocaleString('es-BO')} kg · {Number(item.rendimiento_km_l).toLocaleString('es-BO')} km/L</p></div><Badge value={item.disponible ? 'disponible' : 'no_disponible'} /></div><div className='mt-3 flex justify-end gap-1 border-t border-slate-100 pt-3'><Button variant='ghost' size='sm' onClick={() => setEditing(item)}><Edit3 size={16} />Editar</Button><Button variant='ghost' size='sm' className='text-rose-600 hover:bg-rose-50' onClick={() => setDeleting(item)}><Trash2 size={16} />Eliminar</Button></div></article>)}</div><Pagination page={query.data.page} totalPages={query.data.total_pages} total={query.data.total} onChange={setPage} /></>}</Card>
    <Modal open={Boolean(editing)} onOpenChange={(open) => !open && setEditing(null)} title={editing === 'new' ? 'Nuevo vehículo' : 'Editar vehículo'} description='La placa identifica de forma única a cada unidad.'>{editing && <VehicleForm vehicle={editing === 'new' ? undefined : editing} close={() => setEditing(null)} />}</Modal><ConfirmDialog open={Boolean(deleting)} onOpenChange={(open) => !open && setDeleting(null)} title='Eliminar vehículo' description={`Se eliminará ${deleting?.placa ?? 'este vehículo'}. Solo es posible si no participa en una asignación.`} onConfirm={() => deleting && remove.mutate(deleting.id_vehiculo)} busy={remove.isPending} /></div>
}
