export type GeoLocation = { latitude: number; longitude: number; address: string; neighborhood: string; city: string; department: string }
export interface GeocodingProvider { search(query: string, signal?: AbortSignal): Promise<GeoLocation[]>; reverse(latitude: number, longitude: number, signal?: AbortSignal): Promise<GeoLocation> }
type Raw = { lat: string; lon: string; display_name: string; address?: Record<string, string | undefined> }
function normalize(item: Raw): GeoLocation { const a = item.address ?? {}; return { latitude: Number(item.lat), longitude: Number(item.lon), address: item.display_name, neighborhood: a.neighbourhood ?? a.suburb ?? a.city_district ?? '', city: a.city ?? a.town ?? a.village ?? a.municipality ?? '', department: a.state ?? a.region ?? '' } }
const cache = new Map<string, { expires: number; value: GeoLocation[] | GeoLocation }>()
async function cached<T extends GeoLocation[] | GeoLocation>(key: string, load: () => Promise<T>): Promise<T> { const hit = cache.get(key); if (hit && hit.expires > Date.now()) return hit.value as T; const value = await load(); cache.set(key, { expires: Date.now() + 300_000, value }); return value }
export const nominatimProvider: GeocodingProvider = {
  search(query, signal) { return cached(`s:${query.trim().toLowerCase()}`, async () => { const url = new URL('https://nominatim.openstreetmap.org/search'); url.search = new URLSearchParams({ q: query, format: 'jsonv2', addressdetails: '1', countrycodes: 'bo', limit: '5' }).toString(); const response = await fetch(url, { signal, headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('No pudimos buscar esa dirección.'); return ((await response.json()) as Raw[]).map(normalize) }) },
  reverse(latitude, longitude, signal) { return cached(`r:${latitude.toFixed(5)},${longitude.toFixed(5)}`, async () => { const url = new URL('https://nominatim.openstreetmap.org/reverse'); url.search = new URLSearchParams({ lat: String(latitude), lon: String(longitude), format: 'jsonv2', addressdetails: '1' }).toString(); const response = await fetch(url, { signal, headers: { Accept: 'application/json' } }); if (!response.ok) throw new Error('No pudimos detectar la dirección. Puedes completarla manualmente.'); return normalize(await response.json() as Raw) }) },
}
